config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :users

      resources :verybests

      resources :venues

      resources :dishes
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "dishes#index"
  resources :users
  resources :verybests
  resources :venues
  resources :dishes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/verybest.rb
class Verybest < ApplicationRecord
  # Direct associations

  belongs_to :user

  belongs_to :venue

  belongs_to :dish

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    dish.to_s
  end
end

app/controllers/api/v1/verybests_controller.rb
class Api::V1::VerybestsController < Api::V1::GraphitiController
  def index
    verybests = VerybestResource.all(params)
    respond_with(verybests)
  end

  def show
    verybest = VerybestResource.find(params)
    respond_with(verybest)
  end

  def create
    verybest = VerybestResource.build(params)

    if verybest.save
      render jsonapi: verybest, status: :created
    else
      render jsonapi_errors: verybest
    end
  end

  def update
    verybest = VerybestResource.find(params)

    if verybest.update_attributes
      render jsonapi: verybest
    else
      render jsonapi_errors: verybest
    end
  end

  def destroy
    verybest = VerybestResource.find(params)

    if verybest.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: verybest
    end
  end
end

app/controllers/verybests_controller.rb
class VerybestsController < ApplicationController
  before_action :set_verybest, only: %i[show edit update destroy]

  def index
    @q = Verybest.ransack(params[:q])
    @verybests = @q.result(distinct: true).includes(:dish, :venue,
                                                    :user).page(params[:page]).per(10)
  end

  def show; end

  def new
    @verybest = Verybest.new
  end

  def edit; end

  def create
    @verybest = Verybest.new(verybest_params)

    if @verybest.save
      message = "Verybest was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @verybest, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @verybest.update(verybest_params)
      redirect_to @verybest, notice: "Verybest was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @verybest.destroy
    message = "Verybest was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to verybests_url, notice: message
    end
  end

  private

  def set_verybest
    @verybest = Verybest.find(params[:id])
  end

  def verybest_params
    params.require(:verybest).permit(:dish_id, :venue_id, :user_id, :notes,
                                     :timestamp)
  end
end

app/views/verybests/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Verybest #<%= verybest.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Dish</dt>
      <dd>
        <% if @verybest.dish.present? %>
          <%= link_to verybest.dish, verybest.dish %>
        <% end %>
      </dd>

      <dt>Venue</dt>
      <dd>
        <% if @verybest.venue.present? %>
          <%= link_to verybest.venue, verybest.venue %>
        <% end %>
      </dd>

      <dt>User</dt>
      <dd>
        <% if @verybest.user.present? %>
          <%= link_to verybest.user, verybest.user %>
        <% end %>
      </dd>

      <dt>Notes</dt>
      <dd><%= verybest.notes %></dd>

      <dt>Timestamp</dt>
      <dd><%= verybest.timestamp %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back verybest, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_verybest_url(verybest), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to verybest, method: :delete, data: { confirm: "Do you really want to delete this verybest?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(verybest.updated_at) %> ago
  </div>
</div>

app/views/verybests/_form.html.erb
<% was_validated = verybest.errors.any? %>

<%= form_with(model: verybest, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% dish_class = "form-control" %>
    <% dish_was_invalid = verybest.errors.include?(:dish) %>

    <% if was_validated %>
      <% if dish_was_invalid %>
        <% dish_class << " is-invalid" %>
      <% else %>
        <% dish_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :dish_id %>
    <%= f.collection_select :dish_id, Dish.all, :id, :to_s, {}, class: "form-control" %>
    <% if dish_was_invalid %>
      <% verybest.errors.full_messages_for(:dish).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% venue_class = "form-control" %>
    <% venue_was_invalid = verybest.errors.include?(:venue) %>

    <% if was_validated %>
      <% if venue_was_invalid %>
        <% venue_class << " is-invalid" %>
      <% else %>
        <% venue_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :venue_id %>
    <%= f.collection_select :venue_id, Venue.all, :id, :to_s, {}, class: "form-control" %>
    <% if venue_was_invalid %>
      <% verybest.errors.full_messages_for(:venue).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% user_class = "form-control" %>
    <% user_was_invalid = verybest.errors.include?(:user) %>

    <% if was_validated %>
      <% if user_was_invalid %>
        <% user_class << " is-invalid" %>
      <% else %>
        <% user_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if user_was_invalid %>
      <% verybest.errors.full_messages_for(:user).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% note_class = "form-control" %>
    <% note_was_invalid = verybest.errors.include?(:note) %>

    <% if was_validated %>
      <% if note_was_invalid %>
        <% note_class << " is-invalid" %>
      <% else %>
        <% note_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :notes %>
    <%= f.text_field :notes, class: note_class, placeholder: "Enter note" %>
    <% if note_was_invalid %>
      <% verybest.errors.full_messages_for(:note).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% timestamp_class = "form-control" %>
    <% timestamp_was_invalid = verybest.errors.include?(:timestamp) %>

    <% if was_validated %>
      <% if timestamp_was_invalid %>
        <% timestamp_class << " is-invalid" %>
      <% else %>
        <% timestamp_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :timestamp %>
    <%= f.text_field :timestamp, class: timestamp_class, placeholder: "Enter timestamp" %>
    <% if timestamp_was_invalid %>
      <% verybest.errors.full_messages_for(:timestamp).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/verybests/_list_item.html.erb
<%= link_to verybest, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= verybest %>
    <small class="text-muted">
      <%= time_ago_in_words(verybest.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/verybests/_verybests_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "verybests_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :timestamp_cont, "Timestamp contains" %>
    <%= f.text_field :timestamp_cont, :class => "form-control", :placeholder => "Timestamp contains" %>
  </div>

  <div class="form-group">
    <%= f.label :notes_cont, "Notes contains" %>
    <%= f.text_field :notes_cont, :class => "form-control", :placeholder => "Notes contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :dish_name_cont, "Dish name contains" %>
    <%= f.text_field :dish_name_cont, :class => "form-control", :placeholder => "Dish name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :venue_name_cont, "Venue name contains" %>
    <%= f.text_field :venue_name_cont, :class => "form-control", :placeholder => "Venue name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :user_name_cont, "User name contains" %>
    <%= f.text_field :user_name_cont, :class => "form-control", :placeholder => "User name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/verybests" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#verybests_filters">
  Show filters
</a>

app/views/verybests/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Verybest #<%= @verybest.id %>
      </h2>

      <div class="card-body">
        <%= render "form", verybest: @verybest %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/verybests/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Verybests

      <%= link_to new_verybest_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "verybests/verybests_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Verybests

        <%= link_to new_verybest_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @verybests, partial: "list_item", as: :verybest %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @verybests, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/verybests/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Verybest
      </h2>

      <div class="card-body">
        <%= render "form", verybest: @verybest %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/verybests/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @verybest, partial: "card", as: :verybest %>
  </div>
</div>